x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  duckbot:
    image: duckbot:latest
    container_name: duckbot
    env_file: .env
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite+aiosqlite:////app/data/db.sqlite3
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    logging: *default-logging
    
    dns:
      - 223.5.5.5    # 阿里云 DNS
      - 119.29.29.29  # 腾讯云 DNS

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: duckbot-napcat
    ports:
      - "6099:6099"
    volumes:
      - ./napcat/config:/app/napcat/config
      - ./ntqq:/app/.config/QQ
    depends_on:
      - duckbot
    restart: unless-stopped
    logging: *default-logging
